endpoints:
  os-v2-admin:
    kind: openstack
    scope: local
    layouts:
    - hive
    config:
      region_name: RegionOne
      auth:
        username: admin
        password: password
        project_name: admin
        auth_url:  https://keystone-api:5000/v2.0
